### ISSUE TITLE
tRNA input from tRNAscan-SE ?

### ISSUE THREAD

**Issue by V-JJ** [MoradMMokhtar/MegaLTR#1]
Hello!

Thanks for the software, it looks great!

- I would like to ask whether the tRNAs predicted by "tRNAscan-SE" software can be used as an input to the software. 
- We are working with a non-model arthropoda species, so our set of tRNAs is entirely predicted. However, we applied some filters to refine the data and retain only the high confidence set of tRNAs.

Thanks in advance,
Vadim

**Comment by MoradMMokhtar** [comment]
Hello Vadim
Thanks for using MegaLTR
Yes, you can use tRNAs predicted by "tRNAscan-SE" as input if you using the standalone version, while in the webserver this option is not allowed. To use your own tRNA file you have to copy the tRNA fasta file to the bin/tRNA folder and use the option " -T your_fasta_file_name_with_the_extension". Please replace the space in the file name with "_" or "-" because space is not allowed in the file name.

**Comment by V-JJ** [comment]
Great! The first test finished successfully!
Thanks!
